### ISSUE TITLE
Investigate VRS mapping problem with one score set

### ISSUE THREAD

**Issue by jstone-dev** [VariantEffect/dcd_mapping2#12]
The mapping utility encountered errors when processing this score set:

https://mavedb.org/score-sets/urn:mavedb:00000083-c-1

**Comment by sallybg** [comment]
This error occurs because score set urn:mavedb:00000083-c-1 has some variants that are outside of the portion of the target sequence that aligns to the reference genome.

When we align this score set's target sequence to GRCh38, the first 10 bases of the target sequence don't align, because bases 6, 7, 9, and 10 differ from the reference genome. However, there are variants in this score set that occur in the first 10 bases. So, these variants throw errors because they aren't in the aligned region.

Brought this up at the 2024-07-15 MaveDB software meeting, and we decided to handle this issue by not providing post-mapped VRS objects for variants that fall outside the target sequence's mapping range. We will want to generate the pre-mapped VRS object and record the mapping failure and reason. I'll make a separate task for that (some work needs to be done, because we currently don't return a pre-mapped object if the post-mapped object can't be generated) and call this investigation done.

**Comment by bencap** [comment]
Solved via #13
